doctrine:
    dbal:
#        override_url: true
#        url: '%env(resolve:DATABASE_URL)%'
#
#        # IMPORTANT: You MUST configure your server version,
#        # either here or in the DATABASE_URL env var (see .env file)
#        #server_version: '13'
        default_connection: default
        connections:
            # default connection
            # configure these for your database server
            default:
                url: '%env(DATABASE_URL)%'
#                driver: 'pdo_mysql'
                #server_version: '5.7'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

#        dql:
#            numeric_functions:
#                rand: DoctrineExtensions\Query\Mysql\Rand
