index:
    path: /
    controller: App\Controller\DefaultController::index

#cms:
#  path: /{slug}
#  requirements:
#    slug: ".+"
#
#  defaults:
#    _controller: 'App\Controller\DefaultController:cms'
